import React,{useEffect,useMemo,useState}from'react';import{createRoot}from'react-dom/client';import{Upload,Plus,Sparkles,Clock,Gamepad2,Image as ImageIcon,Star,CheckCircle2,Copy,Trash2}from'lucide-react';import'./style.css';
type Asset={id:string,name:string,url:string,kind:string,favorite?:boolean};type Prompt={id:string,title:string,text:string,refs:string[],created:string};
const KEY='competition-hub-v1';const deadline=new Date('2026-10-02T02:59:00Z');
function App(){const[s,setS]=useState<any>(()=>{try{return JSON.parse(localStorage.getItem(KEY)||'null')||{assets:[],prompts:[]}}catch{return{assets:[],prompts:[]}}});const[prompt,setPrompt]=useState('');const[title,setTitle]=useState('');const[refs,setRefs]=useState<string[]>([]);useEffect(()=>localStorage.setItem(KEY,JSON.stringify(s)),[s]);const left=Math.max(0,deadline.getTime()-Date.now());const days=Math.floor(left/86400000);const hours=Math.floor(left%86400000/3600000);
const upload=(e:React.ChangeEvent<HTMLInputElement>)=>{[...(e.target.files||[])].forEach(f=>{const r=new FileReader;r.onload=()=>setS((x:any)=>({...x,assets:[...x.assets,{id:crypto.randomUUID(),name:f.name,url:r.result,kind:'reference'}]}));r.readAsDataURL(f)})};const savePrompt=()=>{if(!prompt.trim())return;setS((x:any)=>({...x,prompts:[{id:crypto.randomUUID(),title:title||'Untitled prompt',text:prompt,refs,created:new Date().toISOString()},...x.prompts]}));setTitle('')};const selected=useMemo(()=>s.assets.filter((a:Asset)=>refs.includes(a.id)),[s.assets,refs]);
return <><header><div><b>AI COMPETITION HUB</b><span> / GAME ART</span></div><div className="deadline"><Clock size={15}/>{days}D {hours}H · OCT 1, 11:59 PM PT</div></header><main><section className="hero"><div className="eyebrow">GMI CLOUD · HY IMAGE 3.5</div><h1>CHANNEL 86<br/><i>Production Terminal</i></h1><p>One workspace for references, prompts, generations and the final Game Art submission.</p><div className="progress"><span style={{width:'12%'}}/></div><small>BUILD PHASE · MASTER REFERENCES</small></section>
<nav>{[['Dashboard','01'],['References','02'],['Prompt Lab','03'],['Generations','04'],['Finalists','05'],['Submission','06']].map(x=><button key={x[0]}><b>{x[1]}</b>{x[0]}</button>)}</nav>
<section><div className="sectionTitle"><div><span>01</span><h2>MASTER REFERENCES</h2></div><label className="add"><Upload size={17}/> UPLOAD<input type="file" accept="image/*" multiple onChange={upload}/></label></div><p className="muted">Upload characters, environments, style frames, logos and UI. Select up to five for a generation.</p><div className="grid">{s.assets.map((a:Asset)=><article className={'asset '+(refs.includes(a.id)?'chosen':'')} key={a.id} onClick={()=>setRefs((r:string[])=>r.includes(a.id)?r.filter(i=>i!==a.id):r.length<5?[...r,a.id]:r)}><img src={a.url}/><div><b>{a.name}</b><small>{refs.includes(a.id)?'REFERENCE SELECTED':'REFERENCE'}</small></div><button onClick={e=>{e.stopPropagation();setS((x:any)=>({...x,assets:x.assets.filter((z:Asset)=>z.id!==a.id)}))}}><Trash2 size={15}/></button></article>)}<label className="drop"><Plus/><b>ADD REFERENCE</b><span>PNG · JPG · WEBP</span><input type="file" accept="image/*" multiple onChange={upload}/></label></div></section>
<section className="lab"><div className="sectionTitle"><div><span>02</span><h2>PROMPT LAB</h2></div><em>{refs.length}/5 REFERENCES</em></div><input className="title" value={title} onChange={e=>setTitle(e.target.value)} placeholder="Prompt name — e.g. Bellweather Key Art v1"/><textarea value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder="Describe the game-art generation..."/><div className="refstrip">{selected.map((a:Asset)=><img key={a.id} src={a.url}/>)}</div><div className="actions"><button onClick={savePrompt}><Copy size={16}/> SAVE PROMPT</button><button className="generate" title="API endpoint is scaffolded next"><Sparkles size={17}/> GENERATE WITH HY IMAGE</button></div></section>
<section><div className="sectionTitle"><div><span>03</span><h2>PROMPT HISTORY</h2></div></div><div className="prompts">{s.prompts.map((p:Prompt)=><article key={p.id}><div><b>{p.title}</b><small>{new Date(p.created).toLocaleString()} · {p.refs.length} refs</small></div><p>{p.text}</p><button onClick={()=>{setPrompt(p.text);setTitle(p.title);setRefs(p.refs)}}>LOAD</button></article>)}</div></section>
<section className="targets"><h2>GAME ART DELIVERABLES</h2>{['Character Sheets','Scene Concepts','Full UI Screens','Creatures','Environments','Maps + Props','Key Art','Workflow Evidence'].map(x=><div><CheckCircle2 size={18}/><span>{x}</span><small>NOT STARTED</small></div>)}</section></main><footer><Gamepad2/> CHANNEL 86 // HY IMAGE LAB <span>LOCAL PROJECT STORAGE ACTIVE</span></footer></>}
createRoot(document.getElementById('root')!).render(<App/>);